# Generated by Django 5.2.10 on 2026-01-13 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_es', models.CharField(max_length=120, verbose_name='Título (ES)')),
                ('title_en', models.CharField(blank=True, max_length=120, verbose_name='Title (EN)')),
                ('slug', models.SlugField(unique=True)),
                ('description_es', models.TextField(blank=True, verbose_name='Descripción (ES)')),
                ('description_en', models.TextField(blank=True, verbose_name='Description (EN)')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='covers/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'title_es'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/')),
                ('title_es', models.CharField(blank=True, max_length=200, verbose_name='Título foto (ES)')),
                ('title_en', models.CharField(blank=True, max_length=200, verbose_name='Photo title (EN)')),
                ('year', models.CharField(blank=True, max_length=10, verbose_name='Año / Year')),
                ('location', models.CharField(blank=True, max_length=120, verbose_name='Ubicación / Location')),
                ('order', models.PositiveIntegerField(default=0)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='portfolio.series')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
